

/* Main.ino file generated by New Project wizard
 *
 * Created:   Wed Apr 10 2024
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */
 
#include <LiquidCrystal.h>
 
LiquidCrystal lcd(8,9,4,5,6,7);
int analogPin = A0;
int adc_key_old;
int adc_key_in;
int NUM_KEYS = 5;
int key = -1;
int adc_key_val[5] = {30,150,360,535,760};
char msgs[5][15] = {
"Right Key Ok",
"Up Key Ok",
"Down Key Ok",
"Left Key Ok",
"Select Key Ok"
};
int get_key(unsigned int input);
void setup()
 {
   Serial.begin(9600);
 // put your setup code here, to run once:
   lcd.begin(16,2);
   lcd.clear();
   lcd.setCursor(0,0);
   lcd.print("Hello world");
   lcd.setCursor(0,1);
   lcd.print("Pls press any key");
   adc_key_old = analogRead(analogPin);
 }

void loop()
 { // put your main code here, to run repeatedly:
   adc_key_in = analogRead(analogPin);
   Serial.println(adc_key_in);
   //lcd.setCursor(0,0);
   //lcd.println(adc_key_in);
   adc_key_in = get_key(adc_key_in);
   lcd.setCursor(0,1);
   lcd.print(msgs[adc_key_in]);
   //lcd.clear();

 }
 
 int get_key(unsigned int input)
 {
   int k = 0;
   for (k = 0; k < NUM_KEYS;k++)
   {
      if(input < adc_key_val[k])
      {
   return k;
      }
   }
   
   if(k >= NUM_KEYS)
   {
      k = -1;
   }
   
   return k;
 }
